services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    restart: always
    volumes:
      # Keep this volume for persistent data storage
      - ./qdrant_data:/qdrant/storage
      # Add this line for snapshots only
      - ./qdrant_snapshots:/qdrant/snapshots

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_api
      POSTGRES_PASSWORD: secret
    ports:
      - "5444:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@uwi.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5052:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
