"""adjusted column name of admintoken from admin

Revision ID: 24eadc7fdacc
Revises: c4850159b30b
Create Date: 2025-05-11 03:08:14.706831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24eadc7fdacc'
down_revision: Union[str, None] = 'c4850159b30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_admin_tokens_admin_id', table_name='admin_tokens')
    op.create_index(op.f('ix_admin_tokens_user_id'), 'admin_tokens', ['user_id'], unique=False)
    op.drop_constraint('admin_tokens_admin_id_fkey', 'admin_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'admin_tokens', 'admins', ['user_id'], ['id'])
    op.drop_column('admin_tokens', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_tokens', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin_tokens', type_='foreignkey')
    op.create_foreign_key('admin_tokens_admin_id_fkey', 'admin_tokens', 'admins', ['admin_id'], ['id'])
    op.drop_index(op.f('ix_admin_tokens_user_id'), table_name='admin_tokens')
    op.create_index('ix_admin_tokens_admin_id', 'admin_tokens', ['admin_id'], unique=False)
    op.drop_column('admin_tokens', 'user_id')
    # ### end Alembic commands ###
