"""add_faculty

Revision ID: 5af77cfda370
Revises: cf542139c9c8
Create Date: 2025-04-21 15:38:20.073443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af77cfda370'
down_revision: Union[str, None] = 'cf542139c9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('faculty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'faculty')
    # ### end Alembic commands ###
