"""Added Course data tables

Revision ID: 6029dfe45dde
Revises: 2fa9c07ad04a
Create Date: 2025-05-09 18:27:32.644017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6029dfe45dde'
down_revision: Union[str, None] = '2fa9c07ad04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ban_id', sa.Integer(), nullable=False),
    sa.Column('term_effective', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('course_number', sa.String(), nullable=False),
    sa.Column('college_code', sa.String(), nullable=True),
    sa.Column('course_title', sa.String(), nullable=True),
    sa.Column('credit_hour_low', sa.Integer(), nullable=True),
    sa.Column('credit_hour_high', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_courses_ban_id'), 'catalog_courses', ['ban_id'], unique=True)
    op.create_table('catalog_prerequisites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('and_or', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['catalog_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_prerequisites')
    op.drop_index(op.f('ix_catalog_courses_ban_id'), table_name='catalog_courses')
    op.drop_table('catalog_courses')
    # ### end Alembic commands ###
