"""Initial schema with CourseGrades

Revision ID: bb7249f1aef8
Revises: b8f0f7b78eb0
Create Date: 2025-04-17 19:39:39.564204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7249f1aef8'
down_revision: Union[str, None] = 'b8f0f7b78eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('course_title', sa.String(), nullable=True),
    sa.Column('credit_hours', sa.Float(), nullable=True),
    sa.Column('grade_earned', sa.String(), nullable=True),
    sa.Column('whatif_grade', sa.String(), nullable=True),
    sa.Column('is_historical', sa.Boolean(), nullable=True),
    sa.Column('earned_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('enrolled_courses', 'whatif_grade')
    op.drop_column('enrolled_courses', 'grade_earned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrolled_courses', sa.Column('grade_earned', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('enrolled_courses', sa.Column('whatif_grade', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('course_grades')
    # ### end Alembic commands ###
