"""added admin token table and adjsuted admin to accommodate

Revision ID: c4850159b30b
Revises: 2fa9c07ad04a
Create Date: 2025-05-10 20:22:34.722148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4850159b30b'
down_revision: Union[str, None] = '2fa9c07ad04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('token_key', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_tokens_admin_id'), 'admin_tokens', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_tokens_token_key'), 'admin_tokens', ['token_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_tokens_token_key'), table_name='admin_tokens')
    op.drop_index(op.f('ix_admin_tokens_admin_id'), table_name='admin_tokens')
    op.drop_table('admin_tokens')
    # ### end Alembic commands ###
