"""add_majors_minors_faculty_to_user

Revision ID: cf542139c9c8
Revises: 6f38c37a757f
Create Date: 2025-04-21 15:36:38.823572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf542139c9c8'
down_revision: Union[str, None] = '6f38c37a757f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('majors', sa.String(), nullable=True))
    op.add_column('users', sa.Column('minors', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'minors')
    op.drop_column('users', 'majors')
    # ### end Alembic commands ###
