"""added login_id to admin to be a ble to login with id number and password

Revision ID: ef379471cad6
Revises: e8a8ad44e369
Create Date: 2025-04-28 00:36:40.386671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef379471cad6'
down_revision: Union[str, None] = 'e8a8ad44e369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('login_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_admins_login_id'), 'admins', ['login_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_login_id'), table_name='admins')
    op.drop_column('admins', 'login_id')
    # ### end Alembic commands ###
