"""add college & department to catalog_courses

Revision ID: f77b2ef207b8
Revises: 79353ed2db61
Create Date: 2025-05-09 19:22:47.324722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77b2ef207b8'
down_revision: Union[str, None] = '79353ed2db61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_courses', sa.Column('college', sa.String(), nullable=True))
    op.add_column('catalog_courses', sa.Column('department', sa.String(), nullable=True))
    op.create_index(op.f('ix_catalog_courses_college'), 'catalog_courses', ['college'], unique=False)
    op.create_index(op.f('ix_catalog_courses_department'), 'catalog_courses', ['department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_courses_department'), table_name='catalog_courses')
    op.drop_index(op.f('ix_catalog_courses_college'), table_name='catalog_courses')
    op.drop_column('catalog_courses', 'department')
    op.drop_column('catalog_courses', 'college')
    # ### end Alembic commands ###
