"""Added course code

Revision ID: fd68b88e7018
Revises: 6029dfe45dde
Create Date: 2025-05-09 18:31:07.361483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd68b88e7018'
down_revision: Union[str, None] = '6029dfe45dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_courses', sa.Column('course_code', sa.String(), nullable=False))
    op.create_index(op.f('ix_catalog_courses_course_code'), 'catalog_courses', ['course_code'], unique=False)
    op.create_unique_constraint('uq_subject_course', 'catalog_courses', ['subject_code', 'course_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subject_course', 'catalog_courses', type_='unique')
    op.drop_index(op.f('ix_catalog_courses_course_code'), table_name='catalog_courses')
    op.drop_column('catalog_courses', 'course_code')
    # ### end Alembic commands ###
